{% set name = "cpp-filesystem" %}
{% set version = "1.5.8" %}
{% set sha256 = "726f8ccb2ec844f4c66cc4b572369497327df31b86c04cefad6b311964107139" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/gulrak/filesystem/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
  host: []  # Empty host dependency section

test:
  commands:
    - test -f ${PREFIX}/include/ghc/filesystem.hpp  # [unix]
    - test -f ${PREFIX}/lib/cmake/ghc_filesystem/ghc_filesystem-config.cmake  # [unix]
    - if not exist %LIBRARY_PREFIX%/include/ghc/filesystem.hpp (exit 1)  # [win]
    - if not exist %LIBRARY_PREFIX%/lib/cmake/ghc_filesystem/ghc_filesystem-config.cmake (exit 1)  # [win]

about:
  home: https://github.com/gulrak/filesystem
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An implementation of C++17 std::filesystem
  description: An implementation of C++17 std::filesystem for C++11 /C++14/C++17 on Windows, macOS, Linux and FreeBSD.

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
