{% set name = "cpp-filesystem" %}
{% set version = "1.5.10" %}
{% set sha256 = "9b96a024679807879fdfb30e46e8e461293666aeeee5fbf7f5af75aeacdfea29" %}
{% set build_number = "0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/gulrak/filesystem/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build_number }}
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - ninja

test:
  commands:
    - test -f ${PREFIX}/include/ghc/filesystem.hpp  # [unix]
    - test -f ${PREFIX}/lib/cmake/ghc_filesystem/ghc_filesystem-config.cmake  # [unix]
    - if not exist %LIBRARY_PREFIX%/include/ghc/filesystem.hpp (exit 1)  # [win]
    - if not exist %LIBRARY_PREFIX%/lib/cmake/ghc_filesystem/ghc_filesystem-config.cmake (exit 1)  # [win]

about:
  home: https://github.com/gulrak/filesystem
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An implementation of C++17 std::filesystem
  description: An implementation of C++17 std::filesystem for C++11 /C++14/C++17 on Windows, macOS, Linux and FreeBSD.
  dev_url: https://github.com/gulrak/filesystem
  doc_url: https://github.com/gulrak/filesystem/blob/master/README.md#documentation
  doc_src_url: https://github.com/gulrak/filesystem/blob/master/README.md

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
