{% set name = "cpp-filesystem" %}
{% set version = "1.3.10" %}
{% set sha256 = "5a7a0d0aab3143b18d0667ce87f577038320e8b147f3e597a43ab8b6a2346ec5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/gulrak/filesystem/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
  host: []  # Empty host dependency section

test:
  commands:
    - test -f ${PREFIX}/include/ghc/filesystem.hpp  # [unix]
    - test -f ${PREFIX}/lib/cmake/ghcFilesystem/ghcFilesystemConfig.cmake  # [unix]
    - if exist %LIBRARY_PREFIX%\include\ghc\filesystem.hpp (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\ghcFilesystemConfig.cmake (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/gulrak/filesystem
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An implementation of C++17 std::filesystem
  description: An implementation of C++17 std::filesystem for C++11 /C++14/C++17 on Windows, macOS, Linux and FreeBSD.

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
