schema_version: 1

context:
  name: cpp-filesystem
  version: 1.5.12
  sha256: 7d62c5746c724d28da216d9e11827ba4e573df15ef40720292827a4dfd33f2e9

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/gulrak/filesystem/archive/v${{ version }}.tar.gz
  sha256: ${{ sha256 }}
  file_name: ${{ name }}-${{ version }}.tar.gz

build:
  number: 1
  skip: win and vc<14

requirements:
  build:
    - ${{ compiler('cxx') }}
    - cmake
    - if: unix
      then: make
  host: []  # Empty host dependency section

tests:
  - script:
      - if: unix
        then: test -f ${PREFIX}/include/ghc/filesystem.hpp
      - if: unix
        then: test -f ${PREFIX}/lib/cmake/ghc_filesystem/ghc_filesystem-config.cmake
      - if: win
        then: if not exist %LIBRARY_PREFIX%/include/ghc/filesystem.hpp (exit 1)
      - if: win
        then: if not exist %LIBRARY_PREFIX%/lib/cmake/ghc_filesystem/ghc_filesystem-config.cmake (exit 1)

about:
  license: MIT
  license_file: LICENSE
  summary: An implementation of C++17 std::filesystem
  description: An implementation of C++17 std::filesystem for C++11 /C++14/C++17 on Windows, macOS, Linux and FreeBSD.
  homepage: https://github.com/gulrak/filesystem

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
