schema_version: 1

context:
  name: cpp-filesystem
  version: 1.5.12

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/gulrak/filesystem/archive/v${{ version }}.tar.gz
  sha256: 7d62c5746c724d28da216d9e11827ba4e573df15ef40720292827a4dfd33f2e9

build:
  number: 1

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cmake
    - ninja

tests:
  - package_contents:
      include: 
        - ghc/filesystem.hpp
      files:
      - if: unix
        then: 
          - lib/cmake/ghc_filesystem/ghc_filesystem-config.cmake
      - if: win
        then: 
          - Library/lib/cmake/ghc_filesystem/ghc_filesystem-config.cmake

about:
  license: MIT
  license_file: LICENSE
  summary: An implementation of C++17 std::filesystem
  description: An implementation of C++17 std::filesystem for C++11 /C++14/C++17 on Windows, macOS, Linux and FreeBSD.
  homepage: https://github.com/gulrak/filesystem

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - baszalmstra
