conda_forge_output_validation: true
build_platform:
  osx_arm64: osx_64
  win_arm64: win_64
  linux_aarch64: linux_64
  linux_ppc64le: linux_64
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
conda_install_tool: pixi
conda_build_tool: rattler-build
